name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # check the following URLs one by one sequentially
          url: https://ancient-forest-87295.herokuapp.com/health
          max-attempts: 2
          retry-delay: 5s
